name: Build and Publish Site

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build
        run: yarn build

      - name: Copy output to docs/
        if: ${{ github.event_name == 'push' }}
        run: cp -R build/dist/www/. docs/

      - name: Publish to build branch
        if: ${{ github.event_name == 'push' }}
        run: |
          set -eux

          git add docs
          git commit -m 'Build'
          git push -f origin HEAD:build
